config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :articles do
    member do
	get 'like'
    end 
    resources :comments do
      member do
        get 'like'
      end
    end
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  include Likeable
  #has_many :comments, dependent: :destroy
  has_many :comments
  validates :title, presence: true, length: { minimum: 5}

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/comments.rb
class Comment < ActiveRecord::Base
  include Likeable
  belongs_to :article
end

app/models/widget.rb
class Widget < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	#http_basic_authenticate_with name: "alvaro", password: "test", except: [:index, :show]

	def index
		@articles = Article.all
	end

	def like
		@article = Article.find(params[:id])
		@article.likeinc
		redirect_to article_path(@article)
	end

	def edit
		@article = Article.find(params[:id])
	end

	def show
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new
	end

	def create

 		@article = Article.new(article_params)

 

 		if @article.save
			redirect_to action: 'show' , id: @article.id 
		else
			render 'new'
		end 
  		#redirect_to root_path
		#redirect_to @article
	end

 	def update 
		@article = Article.find(params[:id])
		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end


	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		redirect_to articles_path
	end

	private

 	 def article_params

  	  	params.require(:article).permit(:title, :text)

 	 end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  #http_basic_authenticate_with name: "alvaro", password: "test", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
   redirect_to article_path(@article)
  end

  def like
    @comment = Comment.find(params[:id])
    @comment.likeinc
    redirect_to article_path(@comment.article)
  end

  private
    def comment_params
       params.require(:comment).permit(:commenter, :body)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :set_widget, only: [:show, :edit, :update, :destroy]

  # GET /widgets
  # GET /widgets.json
  def index
    @widgets = Widget.all
  end

  # GET /widgets/1
  # GET /widgets/1.json
  def show
  end

  # GET /widgets/new
  def new
    @widget = Widget.new
  end

  # GET /widgets/1/edit
  def edit
  end

  # POST /widgets
  # POST /widgets.json
  def create
    @widget = Widget.new(widget_params)

    respond_to do |format|
      if @widget.save
        format.html { redirect_to @widget, notice: 'Widget was successfully created.' }
        format.json { render :show, status: :created, location: @widget }
      else
        format.html { render :new }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /widgets/1
  # PATCH/PUT /widgets/1.json
  def update
    respond_to do |format|
      if @widget.update(widget_params)
        format.html { redirect_to @widget, notice: 'Widget was successfully updated.' }
        format.json { render :show, status: :ok, location: @widget }
      else
        format.html { render :edit }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.json
  def destroy
    @widget.destroy
    respond_to do |format|
      format.html { redirect_to widgets_url, notice: 'Widget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_widget
      @widget = Widget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def widget_params
      params.require(:widget).permit(:name, :description, :stock)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

  <% if @article.errors.any? %>

    <div id="error_explanation">

      <h2>

        <%= pluralize(@article.errors.count, "error") %> prohibited

        this article from being saved:

      </h2>

      <ul>

        <% @article.errors.full_messages.each do |msg| %>

          <li><%= msg %></li>

        <% end %>

      </ul>

    </div>

  <% end %>

 

  <p>

    <%= f.label :title %><br>

    <%= f.text_field :title %>

  </p>

 

  <p>

    <%= f.label :text %><br>

    <%= f.text_area :text %>

  </p>

 

  <p>

    <%= f.submit %>

  </p>

 

<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= form_for :article, url: article_path(@article)  , method: :patch do |f|%>


  <% if @article.errors.any? %>

    <div id="error_explanation">

      <h2>

        <%= pluralize(@article.errors.count, "error") %> prohibited

        this article from being saved:

      </h2>

      <ul>

        <% @article.errors.full_messages.each do |msg| %>

          <li><%= msg %></li>

        <% end %>

      </ul>

    </div>

  <% end %>

 

  <p>

    <%= f.label :title %><br>

    <%= f.text_field :title %>

  </p>

 

  <p>

    <%= f.label :text %><br>

    <%= f.text_area :text %>

  </p>

 

  <p>

    <%= f.submit %>

  </p>

<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<%= link_to 'New Article', new_article_path %>

<table>
 <tr>
  <th>Title</th>
  <th>Text</th>
  <th colspan="2"></th>
 </tr>

 <% @articles.each do |article| %>
  <tr>
   <td><%= article.title %></td>
   <td><%= article.text %></td>
   <td><%= link_to 'Show', article_path(article) %></td>
   <td><%= link_to 'Edit', edit_article_path(article) %></td>
   <td><%= link_to 'Destroy', article_path(article) , method: :delete , data: { confirm: 'Are you sure?'} %></td>
 </tr>
 <% end %>

</table>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= form_for @article do |f| %>

 <% if @article.errors.any? %>
  <div id="error_explanation">
   <h2>
     <%= pluralize(@article.errors.count, "error")%> prohibited this article from being saved:
   </h2>
   <ul>
    <% @article.errors.full_messages.each do |msg|%>
     <li><%= msg %></li>
    <% end %>
   </ul>
  </div>
 <% end %>

 <p>
  <%= f.label :title %><br >
  <%= f.text_field :title %>
 </p>

 <p>
  <%= f.label :text%> <br>
  <%= f.text_area :text%>
 </p>
  
 <p>
  <%= f.submit %>
 </p>

<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
 <strong>Title:</strong>
 <%= @article.title %>
</p>

<p>
 <strong>Text:</strong>
 <%= @article.text %>
</p>

<p>
<strong>Total Likes:</strong> <%= @article.like.to_i %> 
<%= link_to 'Like this article', like_article_path(@article)  %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Back', articles_path %>

<%= link_to 'Edit', edit_article_path(@article)  %>

app/views/comments/_comment.html.erb
<p>

  <strong>Commenter:</strong>

  <%= comment.commenter %>

</p>

 

<p>

  <strong>Comment:</strong>

  <%= comment.body %>

  

</p>


<p>
<strong>Total Comment Likes:</strong> 
<%= comment.like.to_i %>

<%#= link_to "LIKE THIS" , [comment.article, comment], method: :like  %>
<%#= link_to "LIKE THIS" , like_article_comment_path(  comment )  %>
<%#= link_to "Like me", { controller: "comments", action: "like", id: comment.id } %>
<%= link_to 'LIKE', like_article_comment_path(@article, comment) %>


<%#= @article.comment.like %>
<%#= link_to 'Like this comment', like_article_comment_path(@article)  %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment], method: :delete, data: {confirm: 'Are you sure?'}%>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>

  <p>

    <%= f.label :commenter %><br>

    <%= f.text_field :commenter %>

  </p>

  <p>

    <%= f.label :body %><br>

    <%= f.text_area :body %>

  </p>

  <p>

    <%= f.submit %>

  </p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.erb
<h1>Getting Started with Ruby</h1>

<p>
  Welcome!
</p>

app/views/welcome/index.html.erb
<h1>Hello, Rails! *</h1>
<%= link_to 'My Blog', controller: 'articles' %>

app/views/widgets/_form.html.erb
<%= form_for(@widget) do |f| %>
  <% if @widget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

      <ul>
      <% @widget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/widgets/edit.html.erb
<h1>Editing widget</h1>

<%= render 'form' %>

<%= link_to 'Show', @widget %> |
<%= link_to 'Back', widgets_path %>

app/views/widgets/index.html.erb
<h1>Listing widgets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @widgets.each do |widget| %>
      <tr>
        <td><%= widget.name %></td>
        <td><%= widget.description %></td>
        <td><%= widget.stock %></td>
        <td><%= link_to 'Show', widget %></td>
        <td><%= link_to 'Edit', edit_widget_path(widget) %></td>
        <td><%= link_to 'Destroy', widget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Widget', new_widget_path %>

app/views/widgets/new.html.erb
<h1>New widget</h1>

<%= render 'form' %>

<%= link_to 'Back', widgets_path %>

app/views/widgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @widget.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @widget.description %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @widget.stock %>
</p>

<%= link_to 'Edit', edit_widget_path(@widget) %> |
<%= link_to 'Back', widgets_path %>